app:
  name: testname-dev
  mobile: 8989898

skills: java-dev

my:
  greeting: Hello I m from config-server - client-dev profile
  list:
   skills: one, two, three 

db:
    dbUrl: db-url-link - client-dev profile
    dbUsername: usernameDB
    dbPassword: passdb
    dbMaxConnections: 10
    dbConnectionTimeOut: 3600
