app:
  name: testname
  mobile: 8989898

skills: java, js

my:
  greeting: Hello I m from config-server - default profile - new text
  list:
   skills: one, two, three 

db:
    dbUrl: db-url-link
    dbUsername: usernameDB
    dbPassword: passdb
    dbMaxConnections: 10
    dbConnectionTimeOut: 3600
custom:
    message: This is from Git Config-server - default

    
