app:
  name: testname-dev
  mobile: 8989898

skills: java-dev

my:
  greeting: Hello I m from config-server - product-service-default profile
  list:
   skills: one, two, three 
  test: test message from default profile git props
  
db:
    dbUrl: db-url-link - product-service-default profile
    dbUsername: usernameDB
    dbPassword: passdb
    dbMaxConnections: 10
    dbConnectionTimeOut: 3600
custom:
    message: This is from Git Config-server - product-service-default